spring.application.name=${SPRING_APPLICATION_NAME}
server.port=8082

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

auth.jwt.secret=${JWT_SECRET}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=${EUREKA_URL:}
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
#spring.rabbitmq.addresses = ${MQ_NAME} //aws only
#spring.rabbitmq.ssl.enabled=true //aws only

product.service.url=${PRODUCT_SVC_URL:}