apiVersion: v1
kind: Secret
metadata:
  name: shared-infra-secret
  namespace: ecommerce
type: Opaque
stringData:
  POSTGRES_USER: "<POSTGRES_USER>"
  POSTGRES_PASSWORD: "<POSTGRES_PASSWORD>"
  
  DB_USERNAME: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"
  
  RABBITMQ_USERNAME: "<RABBITMQ_USERNAME>"
  RABBITMQ_PASSWORD: "<RABBITMQ_PASSWORD>"
  
  DB_URL_AUTH: "<DB_URL_AUTH>"
  
  DB_URL_PRODUCT: "<DB_URL_PRODUCT>"
  
  DB_URL_ORDER: "<DB_URL_ORDER>"
  
  DB_URL_INVENTORY: "<DB_URL_INVENTORY>"
  
  JWT_SECRET: "<JWT_SECRET>"
  
  