apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ecommerce
spec:
  selector:
    app: inventory-service
  ports:
    - port: "<PORT_NUMBER>"
      targetPort: "<TARGET_PORT_NUMBER>"
