apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-infra-config
  namespace: ecommerce
data:
  POSTGRES_HOST: "<POSTGRES_HOST>"
  POSTGRES_PORT: "<POSTGRES_PORT>"
  POSTGRES_DB: "<POSTGRES_DB>"
  
  REDIS_HOST: "<REDIS_HOST>"
  REDIS_PORT: "<REDIS_PORT>"
  
  MQ_NAME: "<RABBIT_MQ_URL_AWS_NATIVE>"
  
  SPRING_APPLICATION_NAME_AUTH: "auth-service"
  SPRING_APPLICATION_NAME_PRODUCT: "product-service"
  SPRING_APPLICATION_NAME_ORDER: "order-service"
  SPRING_APPLICATION_NAME_INVENTORY: "inventory-service"
  
  
  PRODUCT_SVC_URL: "<REDIS_HOST>"

  EUREKA_CLIENT_ENABLED: "false"
  
  
  
  